version: '3.8'
services:
    jave-maven-app:
      image: 
      port: 
        - 8080:8080
    postgres:
       image: postgres:13 
       port:
          - 5432:5432
        environment:
          - POSTGRES_PASSWORD:my-pwd
          
