version: '3.8'
services:
    java-maven-app:
      image: flokiboats/my-repo:java-maven-1.0
      ports:
        - 8081:8080
    postgres:
      image: postgres:13
      ports:
        - 5432:5432
      environment:
        - POSTGRES_PASSWORD=my-pwd
